import type { Metadata } from "next";
import "./styles/globals.css";
import { DynamicHeader } from "./components/DynamicHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={` antialiased`}>
        <div className="min-h-screen bg-background">
          <DynamicHeader />
          {children}
        </div>
      </body>
    </html>
  );
}
